name: hierarchical-clustering-moons-env
channels:
  - conda-forge
  - default
dependencies:
  - python=3.8.18
  - numPy=1.24.3
  - pandas=2.0.3
  - matplotlib=3.7.2
  - scikit-learn=1.3.2
  - folium=0.18.0
  - yellowbrick=1.5
